<?php if($this->error):?>
<div class="ui-widget">
<div class="ui-state-error ui-corner-all" style="padding: .7em;">
<p><span class="ui-icon ui-icon-alert"
	style="float: left; margin-right: .3em;"></span> <strong>Error message:</strong><br />
<div style="padding-left: 20px;color:#D94736;font-weight: bold;">
<?php foreach($this->error as $error){echo '- '.$error.'<br/>';}?>
</div>
</p>
</div>
</div>
<?php endif;?>

<div id="tabs">
<ul>
	<li><a href="#tabs-1">Thông tin cơ bản</a></li>	
</ul>
<form action="" method="post" enctype="multipart/form-data">
<div id="tabs-1" class="hastable">
<table>
	<tr>
		<td width="130"><span style="color:#CC0000;">*</span>Màu sắc xe</td>
		<td><?php echo $this->formText('car_paint_color',$this->Color->car_paint_color,array('size'=>60 ))?></td>
	</tr>
	<tr>
		<td width="130">Hình ảnh</td>
		<td><?php echo $this->formFile('image',$_REQUEST['image'])?> <hr />
		Ảnh đã upload: &nbsp; <img width="120" height="80" alt="" src="<?php echo $this->Color->getThumbImage();?>">
		</td>
	</tr>				
</table>
</div>
<input type="submit" value="Lưu lại" class="ui-button ui-widget ui-state-default ui-corner-all"/>
<input type="button" value="Quay lại" onclick="javascript:history.back();" />
</form>
</div>
