<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<base href="http://<?php echo $_SERVER['HTTP_HOST'].$this->baseUrl()?>/admin/" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headMeta(); ?> 
	<?php echo $this->headTitle(); ?> 
    <link href="/css/admin.css" rel="stylesheet" media="all" type="text/css" />    
	<script type="text/javascript" src="/js/tiny_mce/tiny_mce.js"></script>
    <script type="text/javascript" src="/js/jquery-1.4.2.min.js"></script>    
    <script type="text/javascript" src="/js/admin.js"></script>
    <script type="text/javascript" src="/js/superfish.js"></script>
    <script type="text/javascript" src="/js/jquery-ui-1.8.1.custom.min.js"></script>
    <script type="text/javascript" src="/js/tooltip.js"></script>
    <script type="text/javascript" src="/js/tablesorter.js"></script>
    <script type="text/javascript" src="/js/tablesorter-pager.js"></script>
    <script type="text/javascript" src="/js/cookie.js"></script>
    <script type="text/javascript" src="/js/custom.js"></script>      
    <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=<?php echo Zend_Registry::get('Setting')->GOOGLE_API_KEY?>"
      type="text/javascript"></script>
    <script type="text/javascript" src="/js/gmap.js"></script>
     <!--[if IE 6]>
	<link href="/css/admin/ie6.css" rel="stylesheet" media="all" />
	<script src="/js/pngfix.js"></script>
	<script>
	  /* EXAMPLE */
	  DD_belatedPNG.fix('.logo, .other ul#dashboard-buttons li a');
	</script>
	<![endif]-->
    <!--[if IE 7]>
	<link href="/css/admin/ie7.css" rel="stylesheet" media="all" />
	<![endif]-->
<script>
DOMAIN_NAME = "http://<?php echo $_SERVER['HTTP_HOST'].$this->baseUrl()?>/admin/";
</script>
</head>
<body>
<?php $Member = $_SESSION['Member']?>
    <div id="header">
        <div id="top-menu">            
             <span>Logged in as <a title="Logged in as admin"><?php echo $Member['name']?></a></span> | 
             <a href="<?php echo $this->url(array('controller'=>'member', 'action'=>'profile', 'module'=>'admin','id'=>$id))?>" title="My profile">Edit profile</a> | 
             <a href="<?php echo $this->url(array('controller'=>'member','action'=>'logout','module'=>'admin'),'',true)?>"  title="Logout">Logout</a> | 
             <a target="_blank" href="<?php echo $this->url(array('controller'=>'index','action'=>'index','module'=>'default'),'',true)?>"  title="Logout">View site</a>
        </div>
        <div id="sitename">
            <a href="/admin" class="logo float-left" title="Admintasia">Administrator</a>
              <?php echo My_Plugin_Libs::getSplash()?>
            <div class="button float-right"></div>
        </div>
        
        <ul id="navigation" class="sf-navbar sf-js-enabled">         
            <li><a href="<?php echo $this->url(array('controller'=>'content',	'action'=>'index','module'=>'admin'),'',true)?>">Content</a></li>
            <li><a href="<?php echo $this->url(array('controller'=>'trainers',	'action'=>'index','module'=>'admin'),'',true)?>">Trainers</a></li> 
            <li><a href="<?php echo $this->url(array('controller'=>'contact',	'action'=>'index','module'=>'admin'),'',true)?>">Contact</a></li>           
          <!-- Member and System manager -->
          <!-- open if update system -->
          <!-- 
            <li class=""><a href="<?php echo $this->url(array('controller'=>'member',	'action'=>'index','module'=>'admin'),'',true)?>" class="sf-with-ul">Member</a>
               
                <ul style="display: none; visibility: hidden;">
               		<li><a href="<?php echo $this->url(array('controller'=>'group',       'action'=>'index','module'=>'admin'),'',true)?>">Group user</a>
	                    <ul>
	                   	 	<li><a href="<?php echo $this->url(array('controller'=>'group','action'=>'create','module'=>'admin'),'',true)?>">Add group</a></li>                    
	                    </ul>
                    </li> 
                    <li><a href="<?php echo $this->url(array('controller'=>'member',	'action'=>'create','module'=>'admin'),'',true)?>">Add user</a> </li>                   
                    <li><a href="<?php echo $this->url(array('controller'=>'member',	'action'=>'index','module'=>'admin'),'',true)?>">List user</a> </li>
                    <li><a href="<?php echo $this->url(array('controller'=>'member',	'action'=>'history','module'=>'admin'),'',true)?>">History</a> </li>
                </ul>
            </li>            
            <li class=""><a class="sf-with-ul" href="#">Manager system</a>
                <ul style="display: none; visibility: hidden;">
                 	<li><a href="<?php echo $this->url(array('controller'=>'settings',	'action'=>'home','module'=>'admin'),'',true)?>">Homepage</a></li>
                    <li><a href="<?php echo $this->url(array('controller'=>'settings',	'action'=>'footer','module'=>'admin'),'',true)?>">Footer</a> </li>
                    <li><a href="<?php echo $this->url(array('controller'=>'settings', 'action'=>'index','module'=>'admin'),'',true)?>">Setting</a> </li>
                </ul>
            </li>
            --> 
        </ul>
    </div>
    <div id="page-wrapper">
        <div id="main-wrapper">
        	<div id="main-content">
        	<div class="title">
			<h3><?php echo $this->Title ?> </h3>
			</div>
            <?php echo $this->layout()->content; ?>
            </div>
            <div class="clearfix">
            </div>
        </div>
    </div>
    <div class="clearfix">
    </div>
    <div id="footer">
        <div id="menu">
            <a target="_blank" href="<?php echo $this->url(array('controller'=>'index','action'=>'index','module'=>'default'),'',true)?>" title="Home">Home</a><a href="#" title="Administration">Administration</a>
            <a href="<?php echo $this->url(array('controller'=>'settings', 'action'=>'index','module'=>'admin'),'',true)?>" title="Settings">Settings</a> <a href="#" title="Contact">Contact</a>
        </div>
        <strong>Copyright © 2010 - 2011 QSoft Vietnam Corp.</strong>
    </div> 
</body>
</html>
