<div id="Center"><!-- InstanceBeginEditable name="content" -->
  	  <div class="NamePageLogin">    	
      	<p>Please enter your email registered to your account!</p>
        <div class="LeftLogin">        
        	<h3 class="BgTitleLogin">For gotten password</h3>
            <div class="BgLogin">
            	<div class="LeftInputLogin">
            	<form method="post" action="">
                	<ul>
                    	<li>
                        	<span class="TextLogin">Email</span>
                            <span class="BoxInputLogin"><input type="text" class="InputPhone" name="email"></span>
                            <div class="ClearBoth"></div>
                        </li>                                            
                        <li>
                        	<span class="TextLogin">&nbsp;</span>
                            <span class="BoxInputLogin TextAlign"><input type="submit"  value="Send" name="submit"></span>
                            <div class="ClearBoth"></div>
                        </li>
                        <li>
                        	<span class="TextLogin">&nbsp;</span>                           
                            <div class="ClearBoth"></div>
                        </li>
                    </ul>
                    </form>
                </div>
                <div class="RightInputLogin"><?php echo $this->error?></div>
                <div class="ClearBoth"></div>
            </div>
            <div class="BgBottomLogin">&nbsp;</div>
        </div>
      </div>
    </div>