   	  	<div class="LeftCol"> <?php echo $this->action('menu','customers')?></div>               
                  
            
   	  	<!-- //Left -->
   	  	<!-- InstanceBeginEditable name="content" -->
   	  	<div class="RightCol"> 
       	  <div class="BoxChange">
           	<h3>Change Password</h3>
                <div class="InsiteChangePass">
                <?php echo $this->error?>
                <form name="frm_pass" action="<?php echo $this->url(array(),'customers_password')?>" method="post">                    
               
                
                   
                	<ul>
                   	  <li>
                        	<span class="LeftChange">Curent password</span>
                            <span class="RightChange"><input id="input"  name="input" type="password" class="InputPass" value=""/></span>
                            <div class="ClearBoth"></div>
                      </li>
                        <li>
                        	<span class="LeftChange">New password</span>
                            <span class="RightChange"><input id="new_input" name="new_input" type="password" class="InputPass" value=""/></span>
                            <div class="ClearBoth"></div>
                        </li>
                        <li>
                        	<span class="LeftChange">Confirm password</span>
                            <span class="RightChange"><input id="new_input_confirm" name="new_input_confirm" type="password" class="InputPass" value=""/></span>
                            <div class="ClearBoth"></div>
                        </li>
                        <li>
                       	<span class="LeftChange">&nbsp;</span>
                        <span class="RightChange TextAlign">
                       	<input name="button" type="submit" value="Update" class="ButtonBook"/>
                       	</span></li>
                       	</form>
                        <div class="ClearBoth"></div>
                    </ul>
            </div>
          </div>
        </div>
        
   	  	<!-- //Right -->
   	  	<!-- InstanceEndEditable -->
   	  	<div class="ClearBoth"></div>
       