<div class="block_content_detail">
						<h2 class="items_title"><a><?php echo $this->Content->content_title?></a></h2>
						<span class="items_date"><?php //echo date("d-m-Y H:i:s",strtotime($this->Content->created_date))?></span>
						<div class="items_intro"><?php echo $this->Content->content_summary?></div>
						<div class="items_content">
							<?php echo $this->Content->content_detail?>
						</div>						
						<div class="clear"></div>						
					</div><!--End .block_content_detail-->
       