<div class="block_content_detail">
<h2 class="items_title"><a><?php echo $this->Details->title?></a></h2>
<span class="items_date"><?php echo $this->Details->created_date?></span>
<div class="items_intro"><?php echo $this->Details->description?></div>
<div class="items_content">	
	<div style="margin-bottom: 10px;">
	<?php $Video = Video::getById($this->Details->video_id); echo $Video->link;?>	
	</div>
	<?php echo $this->Details->content?>
</div>
<div class="olderPosts">
	<h2>Các tin khác</h2>
	<?php if($this->Deffirent):?>	
	<ul>
	<?php foreach($this->Deffirent as $deffirent):?>
		<li class="olderPost_list">
			<a href="<?php echo $this->url(array("controller"=>"news","action"=>"details","id"=>$deffirent->id));?>"><?php echo $deffirent->title?></a>
		</li>
	<?php endforeach;?>	
	</ul>
	<?php endif;?>
</div><!--End .olderPosts-->
<div class="clear"></div>

</div><!--End .block_content_detail-->
