<div id="footer">
        	<ul>
            	<li>
                	<h4>Racehorse Trainer</h4>
                	<ul>	
                    	<li>Phone: 1300 163 800</li>
                    	<li><a href="/contact" title="Contact Us">Contact Us</a></li>
                        <li><a href="/content/terms-of-service" title="Terms of Service">Terms of Service</a></li>
                		<li><a href="/content/advertise" title="Advertise">Advertise</a></li>
                    </ul>
                </li>
                <li>
                	<h4>MiStable</h4>
                	<ul>
                    	<li><a href="http://mistable.com.au/" title="Software for Horses Trainers">Software for Horses Trainers</a></li>
                        <li><a href="http://mistable.com.au/product-overview" title="Products">Products</a></li>
                        <li><a href="http://mistable.com.au/features" title="Features">Features</a></li>
                    	<li><a href="http://mistable.com.au/contact" title="Contact MiStable">Contact MiStable</a></li>
                    </ul>
                </li>
                <li>
                	<h4>RacePix</h4>
                	<ul>
                    	<li><a href="http://racepix.com.au/" title="Horse racing photo library">Horse racing photo library</a></li>
                        <li><a href="http://racepix.com.au/about-us" title="About RacePix">About RacePix</a></li>
                        <li><a href="http://mistable.com.au/racepix" title="RacePix and MiStable">RacePix and MiStable</a></li>
                    	<li><a href="/contact" title="Contact RacePix">Contact RacePix</a></li>
                    </ul>
                </li>
                <li>
                	<h4>Group One Jobs</h4>
                    <ul>
                    	<li><a href="http://grouponejobs.com.au/" title="Contact Us">Thoroughbred Racing Jobs</a></li>
                        <li><a href="http://grouponejobs.com.au/employer/" title="Post a job">Post a job</a></li>
                        <li><a href="http://mistable.com.au/group-one-jobs" title="Contact Us">Group One Jobs and MiStable</a></li>
                    	<li><a href="http://grouponejobs.com.au/contact" title="Contact Group One Jobs">Contact Group One Jobs</a></li>
                    </ul>
                </li>
            </ul>
        	<div id="copyright">
        		
            </div>
            
        </div>