<?php if($this->error):?>
<div class="ui-widget">
<div class="ui-state-error ui-corner-all" style="padding: .7em;">
<p><span class="ui-icon ui-icon-alert"
	style="float: left; margin-right: .3em;"></span> <strong>Error message:</strong><br />
<div style="padding-left: 20px">
				<?php foreach($this->error as $error){echo '- '.$error.'<br/>';}?>
				</div>
</p>
</div>
</div>
<?php endif;?>

<div id="tabs">
<ul>
	<li><a href="#tabs-1">Nội dung quảng cáo</a></li>	
</ul>
<form action="" method="post" enctype="multipart/form-data">
<div id="tabs-1" class="hastable">
<table>
	<!--<tr>
		<td width="130"><span style="color:#CC0000;">*</span>Tiêu đề</td>
		<td><?php echo $this->formText('name',$this->Banner->name,array('size'=>60 ))?></td>
	</tr>
	<tr>
		<td width="130">Mô tả</td>
		<td><?php echo $this->formTextarea('description',$this->Banner->description,array('rows'=>5))?></td>
	</tr>-->
	<tr>
		<td width="130">Hình ảnh</td>
		<td><?php echo $this->formFile('images',$_REQUEST['images'])?> <hr/>
		Ảnh đã upload: &nbsp; <img width="170" height="80" alt="" src="<?php echo $this->Banner->getThumbImage();?>">
		</td>
	</tr>	
	<tr>
		<td width="130"><span style="color:#CC0000;">*</span>Link đính kèm</td>
		<td><?php echo $this->formText('link',$this->Banner->link,array('size'=>60 ))?></td>
	</tr>	
</table>
</div>
<input type="submit" value="Lưu lại" class="ui-button ui-widget ui-state-default ui-corner-all"/>
<input type="button" value="Quay lại" onclick="javascript:history.back();" />
</form>
</div>
