<div class="hastable">
<div id="qlqg" style="padding-bottom: 10px;">
<a class="btn_no_text btn ui-state-default ui-corner-all tooltip" href="<?php echo $this->url(array('controller'=>'banner','action'=>'create'))?>">Thêm quảng cáo</a>
</div>
<table cellspacing="0" cellpadding="0" width="100%" class="tbl_list">
	<tbody>
		<thead>
			<!--<th>Tên quảng cáo</th>
			<th>Mô tả</th>-->
			<th>Hình ảnh</th>
			<th>Link đính kèm</th>
			<th>Sửa</th>
			<th>Xóa</th>
		</thead>
		<?php foreach($this->Banner as $Banner):?>
		<tr class="<?php ++$i; echo($i%2)?'first':'second'?>">
			<!--<td><?php echo $Banner->name;?></td>
			<td><?php echo $Banner->description;?></td>-->
			<td align="center"><img style="max-width:250px;" alt="" src="<?php echo $Banner->getThumbImage();?>"></td>
			<td><?php echo $Banner->link;?></td>				
			<td width="30"><a class="btn_no_text btn ui-state-default ui-corner-all tooltip" href="<?php echo $this->url(array('controller'=>'banner','action'=>'edit','id'=>$Banner->id))?>"><span class="ui-icon ui-icon-wrench"></span></a></td>
			<td width="30"><a class="btn_no_text btn ui-state-default ui-corner-all tooltip" href="<?php echo $this->url(array('controller'=>'banner','action'=>'delete','id'=>$Banner->id))?>"><span class="ui-icon ui-icon-circle-close"></span></a></td>
		</tr>
		<?php endforeach;?>
	</tbody>
</table>

<div class="paging"><?php echo $this->Pagination($this->Pager,$this->url().'?page={%page}')?></div>
</div>
<div id="dialog-Review-view" title="Review detail">
<form>
<div id="dialog-Review-view_inner"></div>
</form>
</div>