<?php if($this->error):?>
<div class="ui-widget">
<div class="ui-state-error ui-corner-all" style="padding: .7em;">
<p><span class="ui-icon ui-icon-alert"
	style="float: left; margin-right: .3em;"></span> <strong>Error message:</strong><br />
<div style="padding-left: 20px">
				<?php foreach($this->error as $error){echo '- '.$error.'<br/>';}?>
				</div>
</p>
</div>
</div>
<?php endif;?>
<div class="hastable">
<form action="" method="post">
<table>
<tr>
<?php $option = array("default"=>"Select option to search","firstname"=>"First Name","lastname"=>"Last Name","city"=>"City")?>
<td>Searching</td><td><?php echo $this->formSelect("option",$_REQUEST['option'],null,$option)?>&nbsp;<?php echo $this->formText('textSearch',$_REQUEST['textSearch'],array('size'=>40 ))?>&nbsp;<input type="submit" value="Go" class="ui-button ui-widget ui-state-default ui-corner-all"/></td>
</tr>
</table>
</form>
<div id="qlqg" style="padding-bottom: 10px;">
<a class="btn_no_text btn ui-state-default ui-corner-all tooltip" href="<?php echo $this->url(array('controller'=>'trainers','action'=>'create'))?>">Add new</a>
</div>
<table cellspacing="0" cellpadding="0" width="100%" class="tbl_list">
	<tbody>
		<thead>
			<th>Trainer's Name</th>
			<th>City</th>
			<th>State</th>
			<th>Phone</th>
			<th>Edit</th>
			<th>Delete</th>
		</thead>
		
		<?php foreach($this->Trainers as $trainer):?>
		<tr class="<?php ++$i; echo($i%2)?'first':'second'?>">
			<td><?php echo $trainer->firstName .' '. $trainer->lastName ;?></td>
			<td><?php echo $trainer->city?></td>				
			<td><?php $stateName = State::getById($trainer->stateNo); echo $stateName->name?></td>				
			<td><?php echo $trainer->phone?></td>				
			<td width="30"><a class="btn_no_text btn ui-state-default ui-corner-all tooltip" href="<?php echo $this->url(array('controller'=>'trainers','action'=>'edit','id'=>$trainer->trainersListId))?>"><span class="ui-icon ui-icon-wrench"></span></a></td>
			<td width="30"><a class="btn_no_text btn ui-state-default ui-corner-all tooltip" href="<?php echo $this->url(array('controller'=>'trainers','action'=>'delete','id'=>$trainer->trainersListId))?>"><span class="ui-icon ui-icon-circle-close"></span></a></td>
		</tr>
		<?php endforeach;?>
	
	</tbody>
</table>

<div class="paging"><?php echo $this->Pagination($this->Pager,$this->url().'?page={%page}')?></div>
</div>
<div id="dialog-Review-view" title="Review detail">
<form>
<div id="dialog-Review-view_inner"></div>
</form>
</div>
