<?php

/**
 * Content
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Content extends BaseContent {
	public static function getAll($Condition = array(), $currentPage = 1, $recordPerPage = 20, $orderBy = 'content_id') {
		$Content = Doctrine_Query::create ()->from ( __CLASS__ )->orderBy ( $orderBy );
		foreach ( $Condition as $key => $item ) {
			$Content->addWhere ( $key, $item );
		}
		$pager = new Doctrine_Pager ( $Content, $currentPage, $recordPerPage );
		$Data = $pager->execute ();
		return array ($pager, $Data );
	}
	public static function getById($id = 0) {
		return Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'content_id=?', $id )->execute()->getFirst ();
	}
	public static function getByName($name_plain = "") {
		return Doctrine_Query::create ()->from ( __CLASS__ )->where ( 'name_plain=?', $name_plain )->execute ()->getFirst ();
	}
	public function getCreatedDate() {
		return $this->created_date;
	}
	public function getLink() {
		return Zend_Registry::get('Setting')->DOMAIN . '/content/' . $this->name_plain . Zend_Registry::get('Setting')->page_ext;
	}
}