<?php

/**
 * Settings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Settings extends BaseSettings {
	public static function getValue($key) {
		$Settings = $_SESSION ['Settings'];
		
		if (! isset ( $Settings [$key] )) {
			$Settings = Settings::LoadSettings ();
		}
		return $Settings [$key];
	}
	
	public static function LoadSettings() {
		$Settings = Doctrine_Query::create ()->from ( __CLASS__ )->execute ();
		foreach ( $Settings as $value ) {
			$_SESSION ['Settings'] [$value->code] = $value->value;
		}
		return $_SESSION ['Settings'];
	}
}