<style>
td{padding:3px;}
</style>
<table cellpadding="3" cellspacing="2">
	<tr>
		<td valign="top"><form action="" method="post">
<div class="hastable">
<?php
 foreach ( $this->Data as $i=>$Section ) : ?>
<table width="400" id="table_<?php echo $i?>">
	<thead>
		<tr>
			<td align="right">
				<?php echo $Section->name?>
			</td>
			<td colspan="5">
			<?php echo $this->formHidden ( 'adv[' . $i . '][name]', $Section->name )?>
			Giới hạn: <?php echo $this->formText ( 'adv[' . $i . '][limit]', $Section->limit )?></td>
		</tr>
		<tr>
			<td>Hình ảnh</td>
			<td></td>
			<td>Width</td>
			<td>Height</td>			
			<td>Xóa</td>
		</tr>
	</thead>
	<tbody>
	<?php 
	if($Section->adv)
	$check=$Section->adv->toArray();
	$Adv=(!is_array($check[0]))?array($Section->adv):$Section->adv;
	if($Adv)
	foreach ( $Adv as $n => $item ) :?>
		<tr id="<?php echo 'item_' . $i . '_' . $n?>">
			<td>
			<div id="display_<?php echo $i.'_'.$n?>"></div>
			<script>$('#display_<?php echo $i.'_'.$n?>').html(ParsedAdvHtml('<?php echo $item->file?>','<?php echo $item->type?>','80','500'))</script>
			</td>
			<td>Link:<br /><?php echo $this->formText ( 'adv[' . $i . '][' . $n . '][link]', $item->link,array('size'=>30))?><br />
			File: <br /><?php echo $this->formText ( 'adv[' . $i . '][' . $n . '][file]', $item->file ,array('size'=>30,'class'=>'adv_file'))?></td>
			<td><?php echo $this->formText ( 'adv[' . $i . '][' . $n . '][width]', $item->width,array('size'=>3) )?></td>
			<td><?php echo $this->formText ( 'adv[' . $i . '][' . $n . '][height]', $item->height,array('size'=>3)  )?></td>
			<td><a onclick="$('#<?php echo 'item_' . $i . '_' . $n?>').remove();"
				class="btn_no_text btn ui-state-default ui-corner-all tooltip"><span
				class="ui-icon ui-icon-circle-close"></span></a></td>
		</tr>	
	<?php endforeach;?>
	</tbody>
	<tfoot>
		<tr>
			<td colspan="6"><input type="hidden" id="n_<?php echo $i?>"
				value="<?php echo $n?>" /> <input type="button" value="+"
				onclick="addItem('<?php echo $i?>',<?php echo $n?>);" /></td>
		</tr>
	</tfoot>
</table>
<?php endforeach;?>
<div align="center"><input type="submit" value="Update" /></div>
</div>
</form></td>
		<td valign="top" width="50%" class="hastable">
		<table>
			<thead>
				<tr>
					<td>Danh sách thư viện</td>					
				</tr>
			</thead>
			<tbody style="overflow-y: auto; overflow-x: auto; height: 100%;">
			<?php foreach($this->Adv as $file):?>
				<tr>
					<td>
					<script>document.write(ParsedAdvHtml('/uploads/adv/<?php echo $file['name']?>','<?php echo $file['type']?>','','100%'));</script>
					Link: <?php echo $this->formText ( '',' /uploads/adv/'.$file['name'],array('size'=>'52'))?>
					</td>					
				</tr>
			<?php endforeach;?>
			</tbody>
		</table>
		
		</td>
	</tr>
</table>

<script>
var addItem = function(i,n){
	n = parseInt($('#n_'+i).val())+1;
	html='<tr id="item_' +i+ '_'+n+'">';
	html+='<td><div id="display_'+i+'_'+n+'"></div></td>';
	html+='<td>Link:<br><input type="text" value="" id="rows-0-0-name" size="30" name="adv['+i+']['+n+'][link]"><br/>File:<br><input type="text" value="" size="30" id="rows-0-0-name" name="adv['+i+']['+n+'][file]"></td>';
	html+='<td><input type="text" value="" id="rows-0-0-name" name="adv['+i+']['+n+'][width]"></td>';
	html+='<td><input type="text" value="" id="rows-0-0-value" name="adv['+i+']['+n+'][height]"></td>';
	html+='<td><a class="btn_no_text btn ui-state-default ui-corner-all tooltip" onclick="$(\'#item_'+i+'_'+n+'\').remove();"><span class="ui-icon ui-icon-circle-close"></span></a></td>';
	html+='</tr>';
	$('#table_'+i+' > tbody:last').append(html);
	$('#n_'+i).val(n);
}
</script>