<html><head>
<link type="text/css" rel="stylesheet" href="/base.css">
<link type="text/css" rel="stylesheet" href="/common.css">
</head><body>
<div>
	<p align="center"><a href="javascript:window.close()" class="clsLinkItem">Close</a></p>
	<table width="100%" cellspacing="0" cellpadding="0" border="0" bgcolor="#cccccc" align="center" id="table1">
	<tbody>
	<tr>
		<td bgcolor="#eeeeee" align="left">&nbsp;&nbsp;&nbsp; <font color="#3b4455" style="font-size: 14pt;">Card Security Code Explanation</font></td>
	</tr>
	
</tbody></table><br/>
<font color="#3b4455">
For your safety and security, <b>Hotels-in-Vietnam.com</b> requires that you enter your card verification number, 
if one is available. The verification number is a 3 or 4-digit number printed on your card.</font><p>
<font color="#3b4455">If you are using a Visa, Mastercard, or
Discover card, it is a 3 digit number that appears to the right of your
card number (see below).<br/> 
<img width="156" height="96" src="/images/cvv_card.gif">
<br/><br/>
If you are using an American Express card, the verification number is a
4 digit number that appears on the front of your card, above and either
on the left or right of the card number (see below).<br/>
<img width="196" height="138" src="/images/amex_cvv.gif">
<br/><br/>
If your card does not have a verification number, try another card or leave it 
blank.</font></p>
	<p align="center"><a href="javascript:window.close()" class="clsLinkItem">Close</a></p>
</div>
</body></html>