<div class="hastable">
<form action="" method="get">
<table border="0">
	<tr>
		<td><?php echo $this->formText('keyword',($_GET['keyword'])?$_GET['keyword']:'')?></td>
		<td>Tiêu chí</td>
		<td><?php echo $this->formSelect('condition',$_GET['condition'],array('id'=>'s1'),array('name'=>'Tên thành viên','address'=>'Địa chỉ','email'=>'Email'))?></td>
		<td>Phân loại</td>
		<td><?php echo $this->formSelect('type',$_GET['type'],array(),Groups::getOption(array(''=>'Tất cả')))?></td>
		<td><input type="submit" value="Tìm"
			src="/images/btn_submit.png" /></td>
	</tr>
</table>
</form>

<a href="<?php echo $this->url(array('controller'=>'member','action'=>'create'))?>"><input type="button" value="Thêm thành viên"></input> </a>
<table cellpadding="0" cellspacing="0" width="100%" class="tbl_list">
	<thead>
		<tr>
			<th>Username</th>
			<th>Tên thành viên</th>
			<th>Địa Chỉ</th>
			<th>Email</th>
			<th>Số điện thoại</th>
			<th>Phân loại</th>
			<th>Kích hoạt</th>
			<th>Ngày tạo</th>
			<th>Đăng nhập cuối</th>
			<th>Sửa</th>
			<th>Xóa</th>
		</tr>
	</thead>
    <?php foreach($this->Members as $Member):?>
    <tr>
    	<td><?php echo $Member->username?></td>
		<td><?php echo $Member->name?></td>
		<td><?php echo $Member->address?></td>
		<td><?php echo $Member->email?></td>
		<td><?php echo $Member->tel?></td>
		<td><?php echo $Member->getMemberType()?></td>
		<td><?php echo ($Member->status)?'Yes':'No'?></td>
		<td><?php echo $Member->getCreatedDate()?></td>
		<td><?php echo $Member->getLastLogin()?></td>
		<td><a href="<?php echo $this->url(array('controller'=>'member','action'=>'edit','id'=>$Member->id))?>"><span class="ui-icon ui-icon-wrench"></span></a></td>
		<td><a href="<?php echo $this->url(array('controller'=>'member','action'=>'delete','id'=>$Member->id))?>"><span class="ui-icon ui-icon-circle-close"></span></a></td>
	</tr>
    <?php endforeach;?>
</table>

<div class="paging"><?php echo $this->Pagination($this->Pager,'?page={%page}{%Condition}')?></div>

</div>
<script type="text/javascript">
$(function() {
<?php if($_GET['countries_id']):?>
ajaxLoadForOption('<?php echo $this->url(array('controller'=>'ajax','action'=>'getCitiesByCountry'))?>?country=<?php echo $_GET['countries_id']?>',$("#mathanhpho"));
	//$("#mathanhpho").val(<?php echo $_GET['city_id']?>);
	setTimeout('$("#mathanhpho").val(3);',300);
	<?php endif;?>
	$("#maquocgia").change(function() {
		ajaxLoadForOption('<?php echo $this->url(array('controller'=>'ajax','action'=>'getCitiesByCountry'))?>?country='+$("#maquocgia").val(),$("#mathanhpho"));
	})
});
</script>