<?php if($this->error):?>
<div class="ui-widget">
<div class="ui-state-error ui-corner-all" style="padding: .7em;">
<p><span class="ui-icon ui-icon-alert"
	style="float: left; margin-right: .3em;"></span> <strong>Error message:</strong><br />
<div style="padding-left: 20px">
				<?php foreach($this->error as $error){echo '- '.$error.'<br/>';}?>
				</div>
</p>
</div>
</div>
<?php endif;?>

<div id="tabs">
<ul>
	<li><a href="#tabs-1">Nội dung tin tức</a></li>	
</ul>
<form action="" method="post" enctype="multipart/form-data">
<div id="tabs-1" class="hastable">
<table>
	<tr>
		<td width="130"><span style="color:#CC0000;">*</span>Tiêu đề</td>
		<td><?php echo $this->formText('title',$this->News->title,array('size'=>60 ))?></td>
	</tr>
	<tr>
		<td width="130">Mô tả</td>
		<td><?php echo $this->formTextarea('description',$this->News->description,array('rows'=>5))?></td>
	</tr>
	<tr>
		<td width="130"><span style="color:#CC0000;">*</span>Nội dung</td>
		<td><?php echo $this->formTextarea('content',$this->News->content,array('rows'=>5,'class'=>'mceEditor'))?></td>
	</tr>
	<tr>
		<td width="130">Hình ảnh</td>
		<td><?php echo $this->formFile('images',$_REQUEST['images'])?> <hr/>
		Ảnh đã upload: &nbsp; <img width="150" height="120" alt="" src="<?php echo $this->News->getThumbImage();?>">
		</td>
	</tr>
	<tr>
		<td width="130">Nhóm tin</td>
		<td><?php $group = Newgroup::getOption(); echo $this->formSelect('group_id',$this->News->group_id,null,$group)?> </td>
	</tr>
	<tr>
		<td width="130">Video đính kèm</td>
		<td><?php $video = Video::getOption(array('--Hãy chọn video--')); echo $this->formSelect('video_id',$this->News->video_id?$this->News->video_id:"",null,$video)?> </td>
	</tr>
	<tr>
		<td width="130">Trạng thái</td>
		<td><?php $status = array("1"=>"Yes","0"=>"No"); echo $this->formSelect('status',$this->News->status,null,$status)?> </td>
	</tr>	
</table>
</div>
<input type="submit" value="Lưu lại" class="ui-button ui-widget ui-state-default ui-corner-all"/>
<input type="button" value="Quay lại" onclick="javascript:history.back();" />
</form>
</div>
