<div class="hastable">
<div id="qlqg" style="padding-bottom: 10px;">
<a class="btn_no_text btn ui-state-default ui-corner-all tooltip" href="<?php echo $this->url(array('controller'=>'news','action'=>'create'))?>">Thêm tin tức</a>
</div>
<table cellspacing="0" cellpadding="0" width="100%" class="tbl_list">
	<tbody>
		<thead>
			<th>Tiêu đề tin tức</th>
			<th>Mô tả tin tức</th>
			<th>Nhóm tin</th>
			<th>Trạng thái</th>
			<th>Sửa</th>
			<th>Xóa</th>
		</thead>
		<?php foreach($this->News as $Content):?>
		<tr class="<?php ++$i; echo($i%2)?'first':'second'?>">
			<td style="line-height:20px;"width="250"><?php echo $Content->title?></td>
			<td style="line-height:20px;"><?php echo $Content->description?></td>
			<td style="line-height:20px;"width="200"><?php $Group = Newgroup::getById($Content->group_id); echo $Group->name;?></td>
			<td width="60" align="center"><?php echo ($Content->status?"Yes":"No")?></td>				
			<td><a class="btn_no_text btn ui-state-default ui-corner-all tooltip" href="<?php echo $this->url(array('controller'=>'news','action'=>'edit','id'=>$Content->id))?>"><span class="ui-icon ui-icon-wrench"></span></a></td>
			<td width="30"><a class="btn_no_text btn ui-state-default ui-corner-all tooltip" href="<?php echo $this->url(array('controller'=>'news','action'=>'delete','id'=>$Content->id))?>"><span class="ui-icon ui-icon-circle-close"></span></a></td>
		</tr>
		<?php endforeach;?>
	</tbody>
</table>

<div class="paging"><?php echo $this->Pagination($this->Pager,$this->url().'?page={%page}')?></div>
</div>
<div id="dialog-Review-view" title="Review detail">
<form>
<div id="dialog-Review-view_inner"></div>
</form>
</div>
<script type="text/javascript">
	(function() {
    initContentDialog();
	});
	$('#tim').val('<?php echo $this->filterType?>');

</script>