<?php if($this->error):?>
    <div class="response-msg error ui-corner-all">
          <span>Có lỗi:</span> <?php foreach($this->error as $error){echo '- '.$error.'<br/>';}?>
    </div>
<?php endif;?>
<h3 align="center" style="color:#00CCFF; font-size: 14px; font-weight: bold;">Tạo thêm thành viên</h3>
<form method="post" name="member"><input type="hidden" name="id"
	value="<?php echo $this->Customer->id?>" />
<center>	
<table align="center" border="1" style="" width="450px">
	<tr>
		<td style="padding-top: 10px">Email</td>
		<td style="padding-top: 10px"><?php echo $this->formText('email',$this->Member->email,array('size'=>'30'))?></td>
	</tr>
	<tr>
		<td style="padding-top: 10px">Password</td>
		<td style="padding-top: 10px"><?php echo $this->formPassword('password',$this->Member->password,array('size'=>'30'))?></td>
	</tr>
	<tr>
		<td style="padding-top: 10px">Confirm Password</td>
		<td style="padding-top: 10px"><?php echo $this->formPassword('confirmpassword','',array('size'=>'30'))?></td>
	</tr>
	<tr>
		<td style="padding-top: 10px">Tên thành viên</td>
		<td style="padding-top: 10px"><?php echo $this->formText('name',$this->Member->name,array('size'=>'30'))?></td>
	</tr>
	<tr>
		<td style="padding-top: 10px">Chức vụ</td>
		<td style="padding-top: 10px"><?php echo $this->formText('dept',$this->Member->dept,array('size'=>'30'))?></td>
	</tr>
	<tr>
		<td style="padding-top: 10px">Địa chỉ</td>
		<td style="padding-top: 10px"><?php echo $this->formText('address',$this->Member->address,array('size'=>'30'))?></td>
	</tr>
	<tr>
		<td style="padding-top: 10px">Số CMND</td>
		<td style="padding-top: 10px"><?php echo $this->formText('passport_no',$this->Member->passport_no,array('size'=>'30'))?></td>
	</tr>
	<tr>
		<td style="padding-top: 10px">Ngày cấp</td>
		<td style="padding-top: 10px"><?php echo $this->formText('passport_date',$this->Member->passport_date,array('size'=>'30'))?></td>
	</tr>
	<tr>
		<td style="padding-top: 10px">Nơi cấp</td>
		<td style="padding-top: 10px"><?php echo $this->formText('passport_address',$this->Member->passport_address,array('size'=>'30')) ?></td>
	</tr>
	<tr>
		<td style="padding-top: 10px">Mobile</td>
		<td style="padding-top: 10px"><?php echo $this->formText('mobile',$this->Member->mobile,array('size'=>'30'))?></td>
	</tr>
	<tr>
		<td style="padding-top: 10px">Tel/Fax</td>
		<td style="padding-top: 10px"><?php echo $this->formText('tel',$this->Member->tel,array('size'=>'30'))?></td>
	</tr>

	<tr>
		<td style="padding-top: 10px">Phân quyền</td>
		<td style="padding-top: 10px"><?php echo $this->formSelect('member_type',$this->Member->member_type,array(),Groups::getOption())?></td>
	</tr>
	<tr>
		<td style="padding-top: 10px">Trạng thái</td>
		<td style="padding-top: 10px"><?php echo $this->formSelect('status',$this->Member->status,'',array('Disable','Enable'))?></td>
	</tr>
	<tr> 
		<td colspan="2" align="center"><?php echo $this->formSubmit('submit','Cập nhật') ?></td>
	</tr>
</table>
</center>
</form>