 <?php if($this->error):?>
    	<div class="response-msg error ui-corner-all">
               <span>Có lỗi:</span> <?php foreach($this->error as $error){echo '- '.$error.'<br/>';}?>
         </div>
         
<?php endif;?>
<form method="post"><input type="hidden" name="id"
	value="<?php echo $this->Member->id?>" />
<table>
	<tr>
		<td>Email</td>
		<td><?php echo $this->formText('email',$this->Member->email)?></td>
	</tr>
	<tr>
		<td>Password</td>
		<td><?php echo $this->formPassword('password',$this->Member->password)?></td>
	</tr>
	<tr>
		<td>Confirm Password</td>
		<td><?php echo $this->formPassword('confirmpassword','')?></td>
	</tr>
	<tr>
		<td>Tên thành viên</td>
		<td><?php echo $this->formText('name',$this->Member->name)?></td>
	</tr>
	<tr>
		<td>Chức vụ</td>
		<td><?php echo $this->formText('dept',$this->Member->dept)?></td>
	</tr>
	<tr>
		<td>Địa chỉ</td>
		<td><?php echo $this->formText('address',$this->Member->address)?></td>
	</tr>
	<tr>
		<td>Số CMND</td>
		<td><?php echo $this->formText('passport_no',$this->Member->passport_no)?></td>
	</tr>
	<tr>
		<td>Ngày cấp</td>
		<td><?php echo $this->formText('passport_date',$this->Member->passport_date)?></td>
	</tr>
	<tr>
		<td>Nơi cấp</td>
		<td><?php echo $this->formText('passport_address',$this->Member->passport_address)?></td>
	</tr>
	<tr>
		<td>mobile</td>
		<td><?php echo $this->formText('mobile',$this->Member->mobile)?></td>
	</tr>
	<tr>
		<td>Tel/Fax</td>
		<td><?php echo $this->formText('tel',$this->Member->tel)?></td>
	</tr>

	<tr>
		<td>Phân quyền</td>
		<td><?php echo $this->formSelect('member_type',$this->Member->member_type,array(),Groups::getOption())?></td>
	</tr>
	<tr>
		<td>Trạng thái</td>
		<td><?php echo $this->formSelect('status',$this->Member->status,'',array('Disable','Enable'))?></td>
	</tr>
	<tr>
		<td></td>
		<td><?php echo $this->formSubmit('submit','Cập nhật')?></td>
	</tr>
</table>
</form>