<?php if($this->error):?>
<div class="ui-widget">
<div class="ui-state-error ui-corner-all" style="padding: .7em;">
<p><span class="ui-icon ui-icon-alert"
	style="float: left; margin-right: .3em;"></span> <strong>Error message:</strong><br />
<div style="padding-left: 20px">
				<?php foreach($this->error as $error){echo '- '.$error.'<br/>';}?>
				</div>
</p>
</div>
</div>
<?php endif;?>

<div id="tabs">
<ul>
	<li><a href="#tabs-1">Nội dung video</a></li>	
</ul>
<form action="" method="post" enctype="multipart/form-data">
<div id="tabs-1" class="hastable">
<table>
	<tr>
		<td width="130"><span style="color:#CC0000;">*</span>Tên video</td>
		<td><?php echo $this->formText('name',$_REQUEST['name'],array('size'=>60 ))?></td>
	</tr>	
	<tr>
		<td width="130"><span style="color:#CC0000;">*</span>Đường dẫn</td>
		<td>Bạn nhập vào một embed iframe<br/><?php echo $this->formTextarea('link',$_REQUEST['link'],array('rows'=>5))?></td>
	</tr>
	<tr>
		<td width="130">Nhóm tim</td>
		<td><?php $group = NewGroup::getOption();; echo $this->formSelect('group_id',$_REQUEST['group_id'],null,$group)?> </td>
	</tr>
</table>
</div>
<input type="submit" value="Lưu lại" class="ui-button ui-widget ui-state-default ui-corner-all"/>
<input type="button" value="Quay lại" onclick="javascript:history.back();" />
</form>
</div>
