<div class="hastable">
<div id="qlqg" style="padding-bottom: 10px;">
<a class="btn_no_text btn ui-state-default ui-corner-all tooltip" href="<?php echo $this->url(array('controller'=>'product','action'=>'create'))?>">Thêm sản phẩm</a>
</div>
<table cellspacing="0" cellpadding="0" width="100%" class="tbl_list">
	<tbody>
		<thead>
			<th>Tên sản phẩm</th>
			<th>Giá</th>
			<th>Hãng sản xuất</th>
			<th>Nhóm sản phẩm</th>
			<!--<th>Lượt xem</th>-->
			<th>Trạng thái</th>
			<th>Sửa</th>
			<th>Xóa</th>
		</thead>
		<?php foreach($this->Product as $Product):?>
		<tr class="<?php ++$i; echo($i%2)?'first':'second'?>">
			<td><?php echo $Product->product_name?></td>
			<td><?php echo number_format ( $Product->product_price, 0 , '.' , ',' );?>&nbsp;VND</td>				
			<td><?php echo $Product->manufacturer?></td>
			<td><?php $Group = ProductGroup::getById($Product->id_group_product); echo $Group->name;?></td>	
			<!--<td><?php echo $Product->view?></td>-->
			<td><?php echo ($Product->status?"Yes":"No")?></td>		
			<td width="30"><a class="btn_no_text btn ui-state-default ui-corner-all tooltip" href="<?php echo $this->url(array('controller'=>'product','action'=>'edit','id'=>$Product->id))?>"><span class="ui-icon ui-icon-wrench"></span></a></td>
			<td width="30"><a class="btn_no_text btn ui-state-default ui-corner-all tooltip" href="<?php echo $this->url(array('controller'=>'product','action'=>'delete','id'=>$Product->id))?>"><span class="ui-icon ui-icon-circle-close"></span></a></td>
		</tr>
		<?php endforeach;?>
	</tbody>
</table>

<div class="paging"><?php echo $this->Pagination($this->Pager,$this->url().'?page={%page}')?></div>
</div>
<div id="dialog-Review-view" title="Review detail">
<form>
<div id="dialog-Review-view_inner"></div>
</form>
</div>
<script type="text/javascript">
	(function() {
    initContentDialog();
	});
	$('#tim').val('<?php echo $this->filterType?>');

</script>